package builder.sqlCommand;


/**
 * <p> Transaction Control Language queries will be generated by this interface
 *
 * @author alireza_bayat
 */
public interface SQL_TCL<E> {

    //TODO COMMIT
    //TODO ROLLBACK
    //TODO SAVEPOINT

    //SET TRANSACTION
}
