package com.hades.builder.sqlCommand.rules;

/**
 * <p>Data Definition Language queries will be generated by this interface
 *
 * @author alireza_bayat
 */
public interface SQL_DDL<E> {

    //TODO create
    //TODO alter
    //TODO drop
    //TODO truncate

    //ANALYZE
    //ASSOCIATE STATISTICS
    //AUDIT
    //COMMENT
    //DISASSOCIATE STATISTICS
    //FLASHBACK ... (All statements beginning with FLASHBACK)
    //GRANT
    //NOAUDIT
    //PURGE
    //RENAME
    //REVOKE
}
