package com.hades.builder.sqlCommand.rules;


import java.lang.reflect.InvocationTargetException;

import com.hades.builder.sqlCommand.SQLUtils;
import com.hades.model.type.EntityType;

/**
 * <p>Data Manipulation Language queries will be generated by this interface
 *
 * @author alireza_bayat
 */
public interface SQL_DML<E extends EntityType> extends SQLUtils<E> {

    String insert(E e) throws IllegalAccessException, InvocationTargetException;

    String update(E e);

    String delete(E e);


    //CALL
    //EXPLAIN PLAN
    //LOCK TABLE
    //MERGE

}
