package builder.sqlCommand.rules;


/**
 * <p>Data Manipulation Language queries will be generated by this interface
 *
 * @author alireza_bayat
 */
public interface SQL_DML<E> {

    //TODO INSERT
    //TODO UPDATE
    //TODO DELETE

    //CALL
    //EXPLAIN PLAN
    //LOCK TABLE
    //MERGE

}
