package com.hades.builder.sqlCommand;

/**
 * <p>Data Control Language queries will be generated by this interface
 *
 * @author alireza_bayat
 */
public interface SQL_DCL<E> {

    //TODO Grant
    //TODO Revoke

}
